base:
  hosts:
    home-rp1:
      config_dir: /home/zekchan/homeassistant/config
      homeassistant_user: zekchan
      zigbee2mqtt_adapter: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6a30b08e5c51ef1183fd338ccc32aab1-if00-port0
      zigbee2mqtt_user: zekchan